// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	command "github.com/netologist/ai-support-platform/internal/app/command"

	mock "github.com/stretchr/testify/mock"
)

// MockLoginExecutor is an autogenerated mock type for the LoginExecutor type
type MockLoginExecutor struct {
	mock.Mock
}

type MockLoginExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginExecutor) EXPECT() *MockLoginExecutor_Expecter {
	return &MockLoginExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd
func (_m *MockLoginExecutor) Execute(ctx context.Context, cmd command.LoginCommand) (command.LoginResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 command.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, command.LoginCommand) (command.LoginResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, command.LoginCommand) command.LoginResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(command.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, command.LoginCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockLoginExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd command.LoginCommand
func (_e *MockLoginExecutor_Expecter) Execute(ctx interface{}, cmd interface{}) *MockLoginExecutor_Execute_Call {
	return &MockLoginExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd)}
}

func (_c *MockLoginExecutor_Execute_Call) Run(run func(ctx context.Context, cmd command.LoginCommand)) *MockLoginExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.LoginCommand))
	})
	return _c
}

func (_c *MockLoginExecutor_Execute_Call) Return(_a0 command.LoginResult, _a1 error) *MockLoginExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginExecutor_Execute_Call) RunAndReturn(run func(context.Context, command.LoginCommand) (command.LoginResult, error)) *MockLoginExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginExecutor creates a new instance of MockLoginExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginExecutor {
	mock := &MockLoginExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
