// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmbeddingProvider is an autogenerated mock type for the EmbeddingProvider type
type MockEmbeddingProvider struct {
	mock.Mock
}

type MockEmbeddingProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingProvider) EXPECT() *MockEmbeddingProvider_Expecter {
	return &MockEmbeddingProvider_Expecter{mock: &_m.Mock}
}

// Embed provides a mock function with given fields: ctx, text
func (_m *MockEmbeddingProvider) Embed(ctx context.Context, text string) ([]float32, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = rf(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingProvider_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type MockEmbeddingProvider_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockEmbeddingProvider_Expecter) Embed(ctx interface{}, text interface{}) *MockEmbeddingProvider_Embed_Call {
	return &MockEmbeddingProvider_Embed_Call{Call: _e.mock.On("Embed", ctx, text)}
}

func (_c *MockEmbeddingProvider_Embed_Call) Run(run func(ctx context.Context, text string)) *MockEmbeddingProvider_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmbeddingProvider_Embed_Call) Return(_a0 []float32, _a1 error) *MockEmbeddingProvider_Embed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingProvider_Embed_Call) RunAndReturn(run func(context.Context, string) ([]float32, error)) *MockEmbeddingProvider_Embed_Call {
	_c.Call.Return(run)
	return _c
}

// ModelName provides a mock function with no fields
func (_m *MockEmbeddingProvider) ModelName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModelName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEmbeddingProvider_ModelName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModelName'
type MockEmbeddingProvider_ModelName_Call struct {
	*mock.Call
}

// ModelName is a helper method to define mock.On call
func (_e *MockEmbeddingProvider_Expecter) ModelName() *MockEmbeddingProvider_ModelName_Call {
	return &MockEmbeddingProvider_ModelName_Call{Call: _e.mock.On("ModelName")}
}

func (_c *MockEmbeddingProvider_ModelName_Call) Run(run func()) *MockEmbeddingProvider_ModelName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmbeddingProvider_ModelName_Call) Return(_a0 string) *MockEmbeddingProvider_ModelName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingProvider_ModelName_Call) RunAndReturn(run func() string) *MockEmbeddingProvider_ModelName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingProvider creates a new instance of MockEmbeddingProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingProvider {
	mock := &MockEmbeddingProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
