// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/netologist/ai-support-platform/internal/domain/service"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRateLimiter is an autogenerated mock type for the RateLimiter type
type MockRateLimiter struct {
	mock.Mock
}

type MockRateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimiter) EXPECT() *MockRateLimiter_Expecter {
	return &MockRateLimiter_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function with given fields: ctx, key, limit, window
func (_m *MockRateLimiter) Allow(ctx context.Context, key string, limit int64, window time.Duration) (service.RateLimitResult, error) {
	ret := _m.Called(ctx, key, limit, window)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 service.RateLimitResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, time.Duration) (service.RateLimitResult, error)); ok {
		return rf(ctx, key, limit, window)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, time.Duration) service.RateLimitResult); ok {
		r0 = rf(ctx, key, limit, window)
	} else {
		r0 = ret.Get(0).(service.RateLimitResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, time.Duration) error); ok {
		r1 = rf(ctx, key, limit, window)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRateLimiter_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type MockRateLimiter_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - limit int64
//   - window time.Duration
func (_e *MockRateLimiter_Expecter) Allow(ctx interface{}, key interface{}, limit interface{}, window interface{}) *MockRateLimiter_Allow_Call {
	return &MockRateLimiter_Allow_Call{Call: _e.mock.On("Allow", ctx, key, limit, window)}
}

func (_c *MockRateLimiter_Allow_Call) Run(run func(ctx context.Context, key string, limit int64, window time.Duration)) *MockRateLimiter_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockRateLimiter_Allow_Call) Return(_a0 service.RateLimitResult, _a1 error) *MockRateLimiter_Allow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRateLimiter_Allow_Call) RunAndReturn(run func(context.Context, string, int64, time.Duration) (service.RateLimitResult, error)) *MockRateLimiter_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRateLimiter creates a new instance of MockRateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimiter {
	mock := &MockRateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
