// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTicketCache is an autogenerated mock type for the TicketCache type
type MockTicketCache struct {
	mock.Mock
}

type MockTicketCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketCache) EXPECT() *MockTicketCache_Expecter {
	return &MockTicketCache_Expecter{mock: &_m.Mock}
}

// DeleteTicket provides a mock function with given fields: ctx, ticketID
func (_m *MockTicketCache) DeleteTicket(ctx context.Context, ticketID uuid.UUID) error {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTicket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, ticketID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketCache_DeleteTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTicket'
type MockTicketCache_DeleteTicket_Call struct {
	*mock.Call
}

// DeleteTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
func (_e *MockTicketCache_Expecter) DeleteTicket(ctx interface{}, ticketID interface{}) *MockTicketCache_DeleteTicket_Call {
	return &MockTicketCache_DeleteTicket_Call{Call: _e.mock.On("DeleteTicket", ctx, ticketID)}
}

func (_c *MockTicketCache_DeleteTicket_Call) Run(run func(ctx context.Context, ticketID uuid.UUID)) *MockTicketCache_DeleteTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTicketCache_DeleteTicket_Call) Return(_a0 error) *MockTicketCache_DeleteTicket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketCache_DeleteTicket_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTicketCache_DeleteTicket_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicket provides a mock function with given fields: ctx, ticketID
func (_m *MockTicketCache) GetTicket(ctx context.Context, ticketID uuid.UUID) (entity.Ticket, bool, error) {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetTicket")
	}

	var r0 entity.Ticket
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Ticket, bool, error)); ok {
		return rf(ctx, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Ticket); ok {
		r0 = rf(ctx, ticketID)
	} else {
		r0 = ret.Get(0).(entity.Ticket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, ticketID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, ticketID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTicketCache_GetTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicket'
type MockTicketCache_GetTicket_Call struct {
	*mock.Call
}

// GetTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
func (_e *MockTicketCache_Expecter) GetTicket(ctx interface{}, ticketID interface{}) *MockTicketCache_GetTicket_Call {
	return &MockTicketCache_GetTicket_Call{Call: _e.mock.On("GetTicket", ctx, ticketID)}
}

func (_c *MockTicketCache_GetTicket_Call) Run(run func(ctx context.Context, ticketID uuid.UUID)) *MockTicketCache_GetTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTicketCache_GetTicket_Call) Return(_a0 entity.Ticket, _a1 bool, _a2 error) *MockTicketCache_GetTicket_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTicketCache_GetTicket_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Ticket, bool, error)) *MockTicketCache_GetTicket_Call {
	_c.Call.Return(run)
	return _c
}

// SetTicket provides a mock function with given fields: ctx, ticket
func (_m *MockTicketCache) SetTicket(ctx context.Context, ticket entity.Ticket) error {
	ret := _m.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for SetTicket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Ticket) error); ok {
		r0 = rf(ctx, ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketCache_SetTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTicket'
type MockTicketCache_SetTicket_Call struct {
	*mock.Call
}

// SetTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket entity.Ticket
func (_e *MockTicketCache_Expecter) SetTicket(ctx interface{}, ticket interface{}) *MockTicketCache_SetTicket_Call {
	return &MockTicketCache_SetTicket_Call{Call: _e.mock.On("SetTicket", ctx, ticket)}
}

func (_c *MockTicketCache_SetTicket_Call) Run(run func(ctx context.Context, ticket entity.Ticket)) *MockTicketCache_SetTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Ticket))
	})
	return _c
}

func (_c *MockTicketCache_SetTicket_Call) Return(_a0 error) *MockTicketCache_SetTicket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketCache_SetTicket_Call) RunAndReturn(run func(context.Context, entity.Ticket) error) *MockTicketCache_SetTicket_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTicketCache creates a new instance of MockTicketCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketCache {
	mock := &MockTicketCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
