// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthorizer is an autogenerated mock type for the Authorizer type
type MockAuthorizer struct {
	mock.Mock
}

type MockAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizer) EXPECT() *MockAuthorizer_Expecter {
	return &MockAuthorizer_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, principal, resource, action
func (_m *MockAuthorizer) Authorize(ctx context.Context, principal entity.Principal, resource string, action string) error {
	ret := _m.Called(ctx, principal, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Principal, string, string) error); ok {
		r0 = rf(ctx, principal, resource, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorizer_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockAuthorizer_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - principal entity.Principal
//   - resource string
//   - action string
func (_e *MockAuthorizer_Expecter) Authorize(ctx interface{}, principal interface{}, resource interface{}, action interface{}) *MockAuthorizer_Authorize_Call {
	return &MockAuthorizer_Authorize_Call{Call: _e.mock.On("Authorize", ctx, principal, resource, action)}
}

func (_c *MockAuthorizer_Authorize_Call) Run(run func(ctx context.Context, principal entity.Principal, resource string, action string)) *MockAuthorizer_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Principal), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthorizer_Authorize_Call) Return(_a0 error) *MockAuthorizer_Authorize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorizer_Authorize_Call) RunAndReturn(run func(context.Context, entity.Principal, string, string) error) *MockAuthorizer_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorizer creates a new instance of MockAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizer {
	mock := &MockAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
