// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPasswordVerifier is an autogenerated mock type for the PasswordVerifier type
type MockPasswordVerifier struct {
	mock.Mock
}

type MockPasswordVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordVerifier) EXPECT() *MockPasswordVerifier_Expecter {
	return &MockPasswordVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: hash, plainText
func (_m *MockPasswordVerifier) Verify(hash string, plainText string) error {
	ret := _m.Called(hash, plainText)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hash, plainText)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hash string
//   - plainText string
func (_e *MockPasswordVerifier_Expecter) Verify(hash interface{}, plainText interface{}) *MockPasswordVerifier_Verify_Call {
	return &MockPasswordVerifier_Verify_Call{Call: _e.mock.On("Verify", hash, plainText)}
}

func (_c *MockPasswordVerifier_Verify_Call) Run(run func(hash string, plainText string)) *MockPasswordVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordVerifier_Verify_Call) Return(_a0 error) *MockPasswordVerifier_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordVerifier_Verify_Call) RunAndReturn(run func(string, string) error) *MockPasswordVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordVerifier creates a new instance of MockPasswordVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordVerifier {
	mock := &MockPasswordVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
