// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAuditLogger is an autogenerated mock type for the AuditLogger type
type MockAuditLogger struct {
	mock.Mock
}

type MockAuditLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogger) EXPECT() *MockAuditLogger_Expecter {
	return &MockAuditLogger_Expecter{mock: &_m.Mock}
}

// Record provides a mock function with given fields: ctx, entry
func (_m *MockAuditLogger) Record(ctx context.Context, entry entity.AuditLog) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.AuditLog) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogger_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockAuditLogger_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - entry entity.AuditLog
func (_e *MockAuditLogger_Expecter) Record(ctx interface{}, entry interface{}) *MockAuditLogger_Record_Call {
	return &MockAuditLogger_Record_Call{Call: _e.mock.On("Record", ctx, entry)}
}

func (_c *MockAuditLogger_Record_Call) Run(run func(ctx context.Context, entry entity.AuditLog)) *MockAuditLogger_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.AuditLog))
	})
	return _c
}

func (_c *MockAuditLogger_Record_Call) Return(_a0 error) *MockAuditLogger_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogger_Record_Call) RunAndReturn(run func(context.Context, entity.AuditLog) error) *MockAuditLogger_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogger creates a new instance of MockAuditLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogger {
	mock := &MockAuditLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
