// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessagePublisher is an autogenerated mock type for the MessagePublisher type
type MockMessagePublisher struct {
	mock.Mock
}

type MockMessagePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagePublisher) EXPECT() *MockMessagePublisher_Expecter {
	return &MockMessagePublisher_Expecter{mock: &_m.Mock}
}

// PublishJSON provides a mock function with given fields: ctx, topic, key, payload
func (_m *MockMessagePublisher) PublishJSON(ctx context.Context, topic string, key string, payload any) error {
	ret := _m.Called(ctx, topic, key, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, any) error); ok {
		r0 = rf(ctx, topic, key, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessagePublisher_PublishJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishJSON'
type MockMessagePublisher_PublishJSON_Call struct {
	*mock.Call
}

// PublishJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - key string
//   - payload any
func (_e *MockMessagePublisher_Expecter) PublishJSON(ctx interface{}, topic interface{}, key interface{}, payload interface{}) *MockMessagePublisher_PublishJSON_Call {
	return &MockMessagePublisher_PublishJSON_Call{Call: _e.mock.On("PublishJSON", ctx, topic, key, payload)}
}

func (_c *MockMessagePublisher_PublishJSON_Call) Run(run func(ctx context.Context, topic string, key string, payload any)) *MockMessagePublisher_PublishJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(any))
	})
	return _c
}

func (_c *MockMessagePublisher_PublishJSON_Call) Return(_a0 error) *MockMessagePublisher_PublishJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessagePublisher_PublishJSON_Call) RunAndReturn(run func(context.Context, string, string, any) error) *MockMessagePublisher_PublishJSON_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessagePublisher creates a new instance of MockMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagePublisher {
	mock := &MockMessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
