// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "github.com/netologist/ai-support-platform/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenIssuer is an autogenerated mock type for the TokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: principal
func (_m *MockTokenIssuer) Issue(principal entity.Principal) (string, error) {
	ret := _m.Called(principal)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.Principal) (string, error)); ok {
		return rf(principal)
	}
	if rf, ok := ret.Get(0).(func(entity.Principal) string); ok {
		r0 = rf(principal)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(entity.Principal) error); ok {
		r1 = rf(principal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - principal entity.Principal
func (_e *MockTokenIssuer_Expecter) Issue(principal interface{}) *MockTokenIssuer_Issue_Call {
	return &MockTokenIssuer_Issue_Call{Call: _e.mock.On("Issue", principal)}
}

func (_c *MockTokenIssuer_Issue_Call) Run(run func(principal entity.Principal)) *MockTokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.Principal))
	})
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) Return(_a0 string, _a1 error) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) RunAndReturn(run func(entity.Principal) (string, error)) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
