// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAIProvider is an autogenerated mock type for the AIProvider type
type MockAIProvider struct {
	mock.Mock
}

type MockAIProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIProvider) EXPECT() *MockAIProvider_Expecter {
	return &MockAIProvider_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function with given fields: ctx, text, categories
func (_m *MockAIProvider) Classify(ctx context.Context, text string, categories []string) (string, error) {
	ret := _m.Called(ctx, text, categories)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (string, error)); ok {
		return rf(ctx, text, categories)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) string); ok {
		r0 = rf(ctx, text, categories)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, text, categories)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIProvider_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type MockAIProvider_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - categories []string
func (_e *MockAIProvider_Expecter) Classify(ctx interface{}, text interface{}, categories interface{}) *MockAIProvider_Classify_Call {
	return &MockAIProvider_Classify_Call{Call: _e.mock.On("Classify", ctx, text, categories)}
}

func (_c *MockAIProvider_Classify_Call) Run(run func(ctx context.Context, text string, categories []string)) *MockAIProvider_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockAIProvider_Classify_Call) Return(_a0 string, _a1 error) *MockAIProvider_Classify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIProvider_Classify_Call) RunAndReturn(run func(context.Context, string, []string) (string, error)) *MockAIProvider_Classify_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateReply provides a mock function with given fields: ctx, systemPrompt, userPrompt
func (_m *MockAIProvider) GenerateReply(ctx context.Context, systemPrompt string, userPrompt string) (string, error) {
	ret := _m.Called(ctx, systemPrompt, userPrompt)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReply")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, systemPrompt, userPrompt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, systemPrompt, userPrompt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, systemPrompt, userPrompt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIProvider_GenerateReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateReply'
type MockAIProvider_GenerateReply_Call struct {
	*mock.Call
}

// GenerateReply is a helper method to define mock.On call
//   - ctx context.Context
//   - systemPrompt string
//   - userPrompt string
func (_e *MockAIProvider_Expecter) GenerateReply(ctx interface{}, systemPrompt interface{}, userPrompt interface{}) *MockAIProvider_GenerateReply_Call {
	return &MockAIProvider_GenerateReply_Call{Call: _e.mock.On("GenerateReply", ctx, systemPrompt, userPrompt)}
}

func (_c *MockAIProvider_GenerateReply_Call) Run(run func(ctx context.Context, systemPrompt string, userPrompt string)) *MockAIProvider_GenerateReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAIProvider_GenerateReply_Call) Return(_a0 string, _a1 error) *MockAIProvider_GenerateReply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIProvider_GenerateReply_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockAIProvider_GenerateReply_Call {
	_c.Call.Return(run)
	return _c
}

// Summarize provides a mock function with given fields: ctx, text
func (_m *MockAIProvider) Summarize(ctx context.Context, text string) (string, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Summarize")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, text)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIProvider_Summarize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Summarize'
type MockAIProvider_Summarize_Call struct {
	*mock.Call
}

// Summarize is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockAIProvider_Expecter) Summarize(ctx interface{}, text interface{}) *MockAIProvider_Summarize_Call {
	return &MockAIProvider_Summarize_Call{Call: _e.mock.On("Summarize", ctx, text)}
}

func (_c *MockAIProvider_Summarize_Call) Run(run func(ctx context.Context, text string)) *MockAIProvider_Summarize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAIProvider_Summarize_Call) Return(_a0 string, _a1 error) *MockAIProvider_Summarize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIProvider_Summarize_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockAIProvider_Summarize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAIProvider creates a new instance of MockAIProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIProvider {
	mock := &MockAIProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
