// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockChunker is an autogenerated mock type for the Chunker type
type MockChunker struct {
	mock.Mock
}

type MockChunker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunker) EXPECT() *MockChunker_Expecter {
	return &MockChunker_Expecter{mock: &_m.Mock}
}

// Chunk provides a mock function with given fields: ctx, content, maxTokens
func (_m *MockChunker) Chunk(ctx context.Context, content string, maxTokens int) ([]string, error) {
	ret := _m.Called(ctx, content, maxTokens)

	if len(ret) == 0 {
		panic("no return value specified for Chunk")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]string, error)); ok {
		return rf(ctx, content, maxTokens)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []string); ok {
		r0 = rf(ctx, content, maxTokens)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, content, maxTokens)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChunker_Chunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chunk'
type MockChunker_Chunk_Call struct {
	*mock.Call
}

// Chunk is a helper method to define mock.On call
//   - ctx context.Context
//   - content string
//   - maxTokens int
func (_e *MockChunker_Expecter) Chunk(ctx interface{}, content interface{}, maxTokens interface{}) *MockChunker_Chunk_Call {
	return &MockChunker_Chunk_Call{Call: _e.mock.On("Chunk", ctx, content, maxTokens)}
}

func (_c *MockChunker_Chunk_Call) Run(run func(ctx context.Context, content string, maxTokens int)) *MockChunker_Chunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockChunker_Chunk_Call) Return(_a0 []string, _a1 error) *MockChunker_Chunk_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChunker_Chunk_Call) RunAndReturn(run func(context.Context, string, int) ([]string, error)) *MockChunker_Chunk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChunker creates a new instance of MockChunker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunker {
	mock := &MockChunker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
