version: "2"

run:
  tests: true
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - testifylint
    - unused
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0