with-expecter: true
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/netologist/ai-support-platform/internal/app/command:
    interfaces:
      LoginExecutor:
        config:
          dir: internal/mocks/command
  github.com/netologist/ai-support-platform/internal/domain/repository:
    interfaces:
      AuthRepository:
        config:
          dir: internal/mocks/repository
  github.com/netologist/ai-support-platform/internal/domain/service:
    interfaces:
      PasswordVerifier:
        config:
          dir: internal/mocks/service
      TokenIssuer:
        config:
          dir: internal/mocks/service
