// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// GetUnsentEvents provides a mock function with given fields: ctx, limit
func (_m *MockOutboxRepository) GetUnsentEvents(ctx context.Context, limit int) ([]*entity.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUnsentEvents")
	}

	var r0 []*entity.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*entity.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*entity.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepository_GetUnsentEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnsentEvents'
type MockOutboxRepository_GetUnsentEvents_Call struct {
	*mock.Call
}

// GetUnsentEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOutboxRepository_Expecter) GetUnsentEvents(ctx interface{}, limit interface{}) *MockOutboxRepository_GetUnsentEvents_Call {
	return &MockOutboxRepository_GetUnsentEvents_Call{Call: _e.mock.On("GetUnsentEvents", ctx, limit)}
}

func (_c *MockOutboxRepository_GetUnsentEvents_Call) Run(run func(ctx context.Context, limit int)) *MockOutboxRepository_GetUnsentEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOutboxRepository_GetUnsentEvents_Call) Return(_a0 []*entity.OutboxEvent, _a1 error) *MockOutboxRepository_GetUnsentEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepository_GetUnsentEvents_Call) RunAndReturn(run func(context.Context, int) ([]*entity.OutboxEvent, error)) *MockOutboxRepository_GetUnsentEvents_Call {
	_c.Call.Return(run)
	return _c
}

// InsertEvent provides a mock function with given fields: ctx, event
func (_m *MockOutboxRepository) InsertEvent(ctx context.Context, event *entity.OutboxEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OutboxEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_InsertEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEvent'
type MockOutboxRepository_InsertEvent_Call struct {
	*mock.Call
}

// InsertEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.OutboxEvent
func (_e *MockOutboxRepository_Expecter) InsertEvent(ctx interface{}, event interface{}) *MockOutboxRepository_InsertEvent_Call {
	return &MockOutboxRepository_InsertEvent_Call{Call: _e.mock.On("InsertEvent", ctx, event)}
}

func (_c *MockOutboxRepository_InsertEvent_Call) Run(run func(ctx context.Context, event *entity.OutboxEvent)) *MockOutboxRepository_InsertEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.OutboxEvent))
	})
	return _c
}

func (_c *MockOutboxRepository_InsertEvent_Call) Return(_a0 error) *MockOutboxRepository_InsertEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_InsertEvent_Call) RunAndReturn(run func(context.Context, *entity.OutboxEvent) error) *MockOutboxRepository_InsertEvent_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEventSent provides a mock function with given fields: ctx, id
func (_m *MockOutboxRepository) MarkEventSent(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkEventSent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_MarkEventSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEventSent'
type MockOutboxRepository_MarkEventSent_Call struct {
	*mock.Call
}

// MarkEventSent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOutboxRepository_Expecter) MarkEventSent(ctx interface{}, id interface{}) *MockOutboxRepository_MarkEventSent_Call {
	return &MockOutboxRepository_MarkEventSent_Call{Call: _e.mock.On("MarkEventSent", ctx, id)}
}

func (_c *MockOutboxRepository_MarkEventSent_Call) Run(run func(ctx context.Context, id string)) *MockOutboxRepository_MarkEventSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOutboxRepository_MarkEventSent_Call) Return(_a0 error) *MockOutboxRepository_MarkEventSent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_MarkEventSent_Call) RunAndReturn(run func(context.Context, string) error) *MockOutboxRepository_MarkEventSent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
