// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTicketRepository is an autogenerated mock type for the TicketRepository type
type MockTicketRepository struct {
	mock.Mock
}

type MockTicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketRepository) EXPECT() *MockTicketRepository_Expecter {
	return &MockTicketRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, ticket
func (_m *MockTicketRepository) Create(ctx context.Context, ticket entity.Ticket) (entity.Ticket, error) {
	ret := _m.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Ticket) (entity.Ticket, error)); ok {
		return rf(ctx, ticket)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Ticket) entity.Ticket); ok {
		r0 = rf(ctx, ticket)
	} else {
		r0 = ret.Get(0).(entity.Ticket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Ticket) error); ok {
		r1 = rf(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTicketRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket entity.Ticket
func (_e *MockTicketRepository_Expecter) Create(ctx interface{}, ticket interface{}) *MockTicketRepository_Create_Call {
	return &MockTicketRepository_Create_Call{Call: _e.mock.On("Create", ctx, ticket)}
}

func (_c *MockTicketRepository_Create_Call) Run(run func(ctx context.Context, ticket entity.Ticket)) *MockTicketRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Ticket))
	})
	return _c
}

func (_c *MockTicketRepository_Create_Call) Return(_a0 entity.Ticket, _a1 error) *MockTicketRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_Create_Call) RunAndReturn(run func(context.Context, entity.Ticket) (entity.Ticket, error)) *MockTicketRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, ticketID
func (_m *MockTicketRepository) GetByID(ctx context.Context, ticketID uuid.UUID) (entity.Ticket, error) {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Ticket, error)); ok {
		return rf(ctx, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Ticket); ok {
		r0 = rf(ctx, ticketID)
	} else {
		r0 = ret.Get(0).(entity.Ticket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTicketRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
func (_e *MockTicketRepository_Expecter) GetByID(ctx interface{}, ticketID interface{}) *MockTicketRepository_GetByID_Call {
	return &MockTicketRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ticketID)}
}

func (_c *MockTicketRepository_GetByID_Call) Run(run func(ctx context.Context, ticketID uuid.UUID)) *MockTicketRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTicketRepository_GetByID_Call) Return(_a0 entity.Ticket, _a1 error) *MockTicketRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Ticket, error)) *MockTicketRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTenant provides a mock function with given fields: ctx, tenantID
func (_m *MockTicketRepository) ListByTenant(ctx context.Context, tenantID uuid.UUID) ([]entity.Ticket, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTenant")
	}

	var r0 []entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Ticket, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Ticket); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_ListByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTenant'
type MockTicketRepository_ListByTenant_Call struct {
	*mock.Call
}

// ListByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockTicketRepository_Expecter) ListByTenant(ctx interface{}, tenantID interface{}) *MockTicketRepository_ListByTenant_Call {
	return &MockTicketRepository_ListByTenant_Call{Call: _e.mock.On("ListByTenant", ctx, tenantID)}
}

func (_c *MockTicketRepository_ListByTenant_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockTicketRepository_ListByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTicketRepository_ListByTenant_Call) Return(_a0 []entity.Ticket, _a1 error) *MockTicketRepository_ListByTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_ListByTenant_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Ticket, error)) *MockTicketRepository_ListByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ticket
func (_m *MockTicketRepository) Update(ctx context.Context, ticket entity.Ticket) (entity.Ticket, error) {
	ret := _m.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Ticket) (entity.Ticket, error)); ok {
		return rf(ctx, ticket)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Ticket) entity.Ticket); ok {
		r0 = rf(ctx, ticket)
	} else {
		r0 = ret.Get(0).(entity.Ticket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Ticket) error); ok {
		r1 = rf(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTicketRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket entity.Ticket
func (_e *MockTicketRepository_Expecter) Update(ctx interface{}, ticket interface{}) *MockTicketRepository_Update_Call {
	return &MockTicketRepository_Update_Call{Call: _e.mock.On("Update", ctx, ticket)}
}

func (_c *MockTicketRepository_Update_Call) Run(run func(ctx context.Context, ticket entity.Ticket)) *MockTicketRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Ticket))
	})
	return _c
}

func (_c *MockTicketRepository_Update_Call) Return(_a0 entity.Ticket, _a1 error) *MockTicketRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_Update_Call) RunAndReturn(run func(context.Context, entity.Ticket) (entity.Ticket, error)) *MockTicketRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ticketID
func (_m *MockTicketRepository) Delete(ctx context.Context, ticketID uuid.UUID) error {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, ticketID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTicketRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID uuid.UUID
func (_e *MockTicketRepository_Expecter) Delete(ctx interface{}, ticketID interface{}) *MockTicketRepository_Delete_Call {
	return &MockTicketRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ticketID)}
}

func (_c *MockTicketRepository_Delete_Call) Run(run func(ctx context.Context, ticketID uuid.UUID)) *MockTicketRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTicketRepository_Delete_Call) Return(_a0 error) *MockTicketRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTicketRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTicketRepository creates a new instance of MockTicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketRepository {
	mock := &MockTicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
