// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDocumentRepository is an autogenerated mock type for the DocumentRepository type
type MockDocumentRepository struct {
	mock.Mock
}

type MockDocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentRepository) EXPECT() *MockDocumentRepository_Expecter {
	return &MockDocumentRepository_Expecter{mock: &_m.Mock}
}

// CreateDocument provides a mock function with given fields: ctx, doc
func (_m *MockDocumentRepository) CreateDocument(ctx context.Context, doc entity.KnowledgeDocument) (entity.KnowledgeDocument, error) {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocument")
	}

	var r0 entity.KnowledgeDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.KnowledgeDocument) (entity.KnowledgeDocument, error)); ok {
		return rf(ctx, doc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.KnowledgeDocument) entity.KnowledgeDocument); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Get(0).(entity.KnowledgeDocument)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.KnowledgeDocument) error); ok {
		r1 = rf(ctx, doc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_CreateDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDocument'
type MockDocumentRepository_CreateDocument_Call struct {
	*mock.Call
}

// CreateDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - doc entity.KnowledgeDocument
func (_e *MockDocumentRepository_Expecter) CreateDocument(ctx interface{}, doc interface{}) *MockDocumentRepository_CreateDocument_Call {
	return &MockDocumentRepository_CreateDocument_Call{Call: _e.mock.On("CreateDocument", ctx, doc)}
}

func (_c *MockDocumentRepository_CreateDocument_Call) Run(run func(ctx context.Context, doc entity.KnowledgeDocument)) *MockDocumentRepository_CreateDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.KnowledgeDocument))
	})
	return _c
}

func (_c *MockDocumentRepository_CreateDocument_Call) Return(_a0 entity.KnowledgeDocument, _a1 error) *MockDocumentRepository_CreateDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_CreateDocument_Call) RunAndReturn(run func(context.Context, entity.KnowledgeDocument) (entity.KnowledgeDocument, error)) *MockDocumentRepository_CreateDocument_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocument provides a mock function with given fields: ctx, id
func (_m *MockDocumentRepository) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type MockDocumentRepository_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDocumentRepository_Expecter) DeleteDocument(ctx interface{}, id interface{}) *MockDocumentRepository_DeleteDocument_Call {
	return &MockDocumentRepository_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument", ctx, id)}
}

func (_c *MockDocumentRepository_DeleteDocument_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDocumentRepository_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDocumentRepository_DeleteDocument_Call) Return(_a0 error) *MockDocumentRepository_DeleteDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_DeleteDocument_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockDocumentRepository_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentByID provides a mock function with given fields: ctx, id
func (_m *MockDocumentRepository) GetDocumentByID(ctx context.Context, id uuid.UUID) (entity.KnowledgeDocument, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentByID")
	}

	var r0 entity.KnowledgeDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.KnowledgeDocument, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.KnowledgeDocument); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.KnowledgeDocument)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_GetDocumentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentByID'
type MockDocumentRepository_GetDocumentByID_Call struct {
	*mock.Call
}

// GetDocumentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDocumentRepository_Expecter) GetDocumentByID(ctx interface{}, id interface{}) *MockDocumentRepository_GetDocumentByID_Call {
	return &MockDocumentRepository_GetDocumentByID_Call{Call: _e.mock.On("GetDocumentByID", ctx, id)}
}

func (_c *MockDocumentRepository_GetDocumentByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDocumentRepository_GetDocumentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDocumentRepository_GetDocumentByID_Call) Return(_a0 entity.KnowledgeDocument, _a1 error) *MockDocumentRepository_GetDocumentByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_GetDocumentByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.KnowledgeDocument, error)) *MockDocumentRepository_GetDocumentByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListDocumentsByTenant provides a mock function with given fields: ctx, tenantID
func (_m *MockDocumentRepository) ListDocumentsByTenant(ctx context.Context, tenantID uuid.UUID) ([]entity.KnowledgeDocument, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for ListDocumentsByTenant")
	}

	var r0 []entity.KnowledgeDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.KnowledgeDocument, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.KnowledgeDocument); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.KnowledgeDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_ListDocumentsByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDocumentsByTenant'
type MockDocumentRepository_ListDocumentsByTenant_Call struct {
	*mock.Call
}

// ListDocumentsByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockDocumentRepository_Expecter) ListDocumentsByTenant(ctx interface{}, tenantID interface{}) *MockDocumentRepository_ListDocumentsByTenant_Call {
	return &MockDocumentRepository_ListDocumentsByTenant_Call{Call: _e.mock.On("ListDocumentsByTenant", ctx, tenantID)}
}

func (_c *MockDocumentRepository_ListDocumentsByTenant_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockDocumentRepository_ListDocumentsByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDocumentRepository_ListDocumentsByTenant_Call) Return(_a0 []entity.KnowledgeDocument, _a1 error) *MockDocumentRepository_ListDocumentsByTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_ListDocumentsByTenant_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.KnowledgeDocument, error)) *MockDocumentRepository_ListDocumentsByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentRepository creates a new instance of MockDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentRepository {
	mock := &MockDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
