// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockChunkRepository is an autogenerated mock type for the ChunkRepository type
type MockChunkRepository struct {
	mock.Mock
}

type MockChunkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunkRepository) EXPECT() *MockChunkRepository_Expecter {
	return &MockChunkRepository_Expecter{mock: &_m.Mock}
}

// InsertChunks provides a mock function with given fields: ctx, chunks
func (_m *MockChunkRepository) InsertChunks(ctx context.Context, chunks []entity.DocumentChunk) error {
	ret := _m.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for InsertChunks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.DocumentChunk) error); ok {
		r0 = rf(ctx, chunks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChunkRepository_InsertChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertChunks'
type MockChunkRepository_InsertChunks_Call struct {
	*mock.Call
}

// InsertChunks is a helper method to define mock.On call
//   - ctx context.Context
//   - chunks []entity.DocumentChunk
func (_e *MockChunkRepository_Expecter) InsertChunks(ctx interface{}, chunks interface{}) *MockChunkRepository_InsertChunks_Call {
	return &MockChunkRepository_InsertChunks_Call{Call: _e.mock.On("InsertChunks", ctx, chunks)}
}

func (_c *MockChunkRepository_InsertChunks_Call) Run(run func(ctx context.Context, chunks []entity.DocumentChunk)) *MockChunkRepository_InsertChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.DocumentChunk))
	})
	return _c
}

func (_c *MockChunkRepository_InsertChunks_Call) Return(_a0 error) *MockChunkRepository_InsertChunks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChunkRepository_InsertChunks_Call) RunAndReturn(run func(context.Context, []entity.DocumentChunk) error) *MockChunkRepository_InsertChunks_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSimilar provides a mock function with given fields: ctx, tenantID, embedding, limit
func (_m *MockChunkRepository) SearchSimilar(ctx context.Context, tenantID uuid.UUID, embedding []float32, limit int) ([]entity.DocumentChunk, error) {
	ret := _m.Called(ctx, tenantID, embedding, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchSimilar")
	}

	var r0 []entity.DocumentChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []float32, int) ([]entity.DocumentChunk, error)); ok {
		return rf(ctx, tenantID, embedding, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []float32, int) []entity.DocumentChunk); ok {
		r0 = rf(ctx, tenantID, embedding, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.DocumentChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []float32, int) error); ok {
		r1 = rf(ctx, tenantID, embedding, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChunkRepository_SearchSimilar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSimilar'
type MockChunkRepository_SearchSimilar_Call struct {
	*mock.Call
}

// SearchSimilar is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - embedding []float32
//   - limit int
func (_e *MockChunkRepository_Expecter) SearchSimilar(ctx interface{}, tenantID interface{}, embedding interface{}, limit interface{}) *MockChunkRepository_SearchSimilar_Call {
	return &MockChunkRepository_SearchSimilar_Call{Call: _e.mock.On("SearchSimilar", ctx, tenantID, embedding, limit)}
}

func (_c *MockChunkRepository_SearchSimilar_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, embedding []float32, limit int)) *MockChunkRepository_SearchSimilar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]float32), args[3].(int))
	})
	return _c
}

func (_c *MockChunkRepository_SearchSimilar_Call) Return(_a0 []entity.DocumentChunk, _a1 error) *MockChunkRepository_SearchSimilar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChunkRepository_SearchSimilar_Call) RunAndReturn(run func(context.Context, uuid.UUID, []float32, int) ([]entity.DocumentChunk, error)) *MockChunkRepository_SearchSimilar_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChunkRepository creates a new instance of MockChunkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunkRepository {
	mock := &MockChunkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
