// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIdempotencyChecker is an autogenerated mock type for the IdempotencyChecker type
type MockIdempotencyChecker struct {
	mock.Mock
}

type MockIdempotencyChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyChecker) EXPECT() *MockIdempotencyChecker_Expecter {
	return &MockIdempotencyChecker_Expecter{mock: &_m.Mock}
}

// IsProcessed provides a mock function with given fields: ctx, key
func (_m *MockIdempotencyChecker) IsProcessed(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for IsProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdempotencyChecker_IsProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProcessed'
type MockIdempotencyChecker_IsProcessed_Call struct {
	*mock.Call
}

// IsProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIdempotencyChecker_Expecter) IsProcessed(ctx interface{}, key interface{}) *MockIdempotencyChecker_IsProcessed_Call {
	return &MockIdempotencyChecker_IsProcessed_Call{Call: _e.mock.On("IsProcessed", ctx, key)}
}

func (_c *MockIdempotencyChecker_IsProcessed_Call) Run(run func(ctx context.Context, key string)) *MockIdempotencyChecker_IsProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIdempotencyChecker_IsProcessed_Call) Return(_a0 bool, _a1 error) *MockIdempotencyChecker_IsProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdempotencyChecker_IsProcessed_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockIdempotencyChecker_IsProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function with given fields: ctx, key
func (_m *MockIdempotencyChecker) MarkProcessed(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIdempotencyChecker_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type MockIdempotencyChecker_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIdempotencyChecker_Expecter) MarkProcessed(ctx interface{}, key interface{}) *MockIdempotencyChecker_MarkProcessed_Call {
	return &MockIdempotencyChecker_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, key)}
}

func (_c *MockIdempotencyChecker_MarkProcessed_Call) Run(run func(ctx context.Context, key string)) *MockIdempotencyChecker_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIdempotencyChecker_MarkProcessed_Call) Return(_a0 error) *MockIdempotencyChecker_MarkProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdempotencyChecker_MarkProcessed_Call) RunAndReturn(run func(context.Context, string) error) *MockIdempotencyChecker_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdempotencyChecker creates a new instance of MockIdempotencyChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyChecker {
	mock := &MockIdempotencyChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
