// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	query "github.com/netologist/ai-support-platform/internal/app/query"
)

// MockSemanticSearchExecutor is an autogenerated mock type for the SemanticSearchExecutor type
type MockSemanticSearchExecutor struct {
	mock.Mock
}

type MockSemanticSearchExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSemanticSearchExecutor) EXPECT() *MockSemanticSearchExecutor_Expecter {
	return &MockSemanticSearchExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd
func (_m *MockSemanticSearchExecutor) Execute(ctx context.Context, cmd query.SemanticSearchQuery) (query.SemanticSearchResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 query.SemanticSearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.SemanticSearchQuery) (query.SemanticSearchResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.SemanticSearchQuery) query.SemanticSearchResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(query.SemanticSearchResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.SemanticSearchQuery) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSemanticSearchExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSemanticSearchExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd query.SemanticSearchQuery
func (_e *MockSemanticSearchExecutor_Expecter) Execute(ctx interface{}, cmd interface{}) *MockSemanticSearchExecutor_Execute_Call {
	return &MockSemanticSearchExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd)}
}

func (_c *MockSemanticSearchExecutor_Execute_Call) Run(run func(ctx context.Context, cmd query.SemanticSearchQuery)) *MockSemanticSearchExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.SemanticSearchQuery))
	})
	return _c
}

func (_c *MockSemanticSearchExecutor_Execute_Call) Return(_a0 query.SemanticSearchResult, _a1 error) *MockSemanticSearchExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSemanticSearchExecutor_Execute_Call) RunAndReturn(run func(context.Context, query.SemanticSearchQuery) (query.SemanticSearchResult, error)) *MockSemanticSearchExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSemanticSearchExecutor creates a new instance of MockSemanticSearchExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSemanticSearchExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSemanticSearchExecutor {
	mock := &MockSemanticSearchExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
