// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	query "github.com/netologist/ai-support-platform/internal/app/query"
)

// MockListDocumentsExecutor is an autogenerated mock type for the ListDocumentsExecutor type
type MockListDocumentsExecutor struct {
	mock.Mock
}

type MockListDocumentsExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListDocumentsExecutor) EXPECT() *MockListDocumentsExecutor_Expecter {
	return &MockListDocumentsExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd
func (_m *MockListDocumentsExecutor) Execute(ctx context.Context, cmd query.ListDocumentsQuery) ([]entity.KnowledgeDocument, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []entity.KnowledgeDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.ListDocumentsQuery) ([]entity.KnowledgeDocument, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.ListDocumentsQuery) []entity.KnowledgeDocument); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.KnowledgeDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.ListDocumentsQuery) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListDocumentsExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockListDocumentsExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd query.ListDocumentsQuery
func (_e *MockListDocumentsExecutor_Expecter) Execute(ctx interface{}, cmd interface{}) *MockListDocumentsExecutor_Execute_Call {
	return &MockListDocumentsExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd)}
}

func (_c *MockListDocumentsExecutor_Execute_Call) Run(run func(ctx context.Context, cmd query.ListDocumentsQuery)) *MockListDocumentsExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.ListDocumentsQuery))
	})
	return _c
}

func (_c *MockListDocumentsExecutor_Execute_Call) Return(_a0 []entity.KnowledgeDocument, _a1 error) *MockListDocumentsExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListDocumentsExecutor_Execute_Call) RunAndReturn(run func(context.Context, query.ListDocumentsQuery) ([]entity.KnowledgeDocument, error)) *MockListDocumentsExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListDocumentsExecutor creates a new instance of MockListDocumentsExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListDocumentsExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListDocumentsExecutor {
	mock := &MockListDocumentsExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
