// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	command "github.com/netologist/ai-support-platform/internal/app/command"

	entity "github.com/netologist/ai-support-platform/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateTicketExecutor is an autogenerated mock type for the CreateTicketExecutor type
type MockCreateTicketExecutor struct {
	mock.Mock
}

type MockCreateTicketExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateTicketExecutor) EXPECT() *MockCreateTicketExecutor_Expecter {
	return &MockCreateTicketExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd
func (_m *MockCreateTicketExecutor) Execute(ctx context.Context, cmd command.CreateTicketCommand) (entity.Ticket, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, command.CreateTicketCommand) (entity.Ticket, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, command.CreateTicketCommand) entity.Ticket); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(entity.Ticket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, command.CreateTicketCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateTicketExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateTicketExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd command.CreateTicketCommand
func (_e *MockCreateTicketExecutor_Expecter) Execute(ctx interface{}, cmd interface{}) *MockCreateTicketExecutor_Execute_Call {
	return &MockCreateTicketExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd)}
}

func (_c *MockCreateTicketExecutor_Execute_Call) Run(run func(ctx context.Context, cmd command.CreateTicketCommand)) *MockCreateTicketExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.CreateTicketCommand))
	})
	return _c
}

func (_c *MockCreateTicketExecutor_Execute_Call) Return(_a0 entity.Ticket, _a1 error) *MockCreateTicketExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateTicketExecutor_Execute_Call) RunAndReturn(run func(context.Context, command.CreateTicketCommand) (entity.Ticket, error)) *MockCreateTicketExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateTicketExecutor creates a new instance of MockCreateTicketExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateTicketExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateTicketExecutor {
	mock := &MockCreateTicketExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
