// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/netologist/ai-support-platform/internal/app/query"
	entity "github.com/netologist/ai-support-platform/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockGetTicketExecutor is an autogenerated mock type for the GetTicketExecutor type
type MockGetTicketExecutor struct {
	mock.Mock
}

type MockGetTicketExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetTicketExecutor) EXPECT() *MockGetTicketExecutor_Expecter {
	return &MockGetTicketExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, qry
func (_m *MockGetTicketExecutor) Execute(ctx context.Context, qry query.GetTicketQuery) (entity.Ticket, error) {
	ret := _m.Called(ctx, qry)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.GetTicketQuery) (entity.Ticket, error)); ok {
		return rf(ctx, qry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.GetTicketQuery) entity.Ticket); ok {
		r0 = rf(ctx, qry)
	} else {
		r0 = ret.Get(0).(entity.Ticket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.GetTicketQuery) error); ok {
		r1 = rf(ctx, qry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Execute is a helper method to define mock.On call
func (_e *MockGetTicketExecutor_Expecter) Execute(ctx interface{}, qry interface{}) *MockGetTicketExecutor_Execute_Call {
	return &MockGetTicketExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, qry)}
}

type MockGetTicketExecutor_Execute_Call struct {
	*mock.Call
}

func (_c *MockGetTicketExecutor_Execute_Call) Return(_a0 entity.Ticket, _a1 error) *MockGetTicketExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetTicketExecutor_Execute_Call) RunAndReturn(run func(context.Context, query.GetTicketQuery) (entity.Ticket, error)) *MockGetTicketExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetTicketExecutor creates a new instance of MockGetTicketExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGetTicketExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetTicketExecutor {
	mock := &MockGetTicketExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
