// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	command "github.com/netologist/ai-support-platform/internal/app/command"
	entity "github.com/netologist/ai-support-platform/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateTicketExecutor is an autogenerated mock type for the UpdateTicketExecutor type
type MockUpdateTicketExecutor struct {
	mock.Mock
}

type MockUpdateTicketExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateTicketExecutor) EXPECT() *MockUpdateTicketExecutor_Expecter {
	return &MockUpdateTicketExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd
func (_m *MockUpdateTicketExecutor) Execute(ctx context.Context, cmd command.UpdateTicketCommand) (entity.Ticket, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, command.UpdateTicketCommand) (entity.Ticket, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, command.UpdateTicketCommand) entity.Ticket); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(entity.Ticket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, command.UpdateTicketCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Execute is a helper method to define mock.On call
func (_e *MockUpdateTicketExecutor_Expecter) Execute(ctx interface{}, cmd interface{}) *MockUpdateTicketExecutor_Execute_Call {
	return &MockUpdateTicketExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd)}
}

type MockUpdateTicketExecutor_Execute_Call struct {
	*mock.Call
}

func (_c *MockUpdateTicketExecutor_Execute_Call) Return(_a0 entity.Ticket, _a1 error) *MockUpdateTicketExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateTicketExecutor_Execute_Call) RunAndReturn(run func(context.Context, command.UpdateTicketCommand) (entity.Ticket, error)) *MockUpdateTicketExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateTicketExecutor creates a new instance of MockUpdateTicketExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUpdateTicketExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateTicketExecutor {
	mock := &MockUpdateTicketExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
