package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/netologist/ai-support-platform/internal/transport/graphql/model"
)

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id string) (*model.Ticket, error) {
	panic(fmt.Errorf("not implemented: Ticket - ticket"))
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context) ([]*model.Ticket, error) {
	panic(fmt.Errorf("not implemented: Tickets - tickets"))
}

// Documents is the resolver for the documents field.
func (r *queryResolver) Documents(ctx context.Context) ([]*model.Document, error) {
	panic(fmt.Errorf("not implemented: Documents - documents"))
}

// SuggestReply is the resolver for the suggestReply field.
func (r *queryResolver) SuggestReply(ctx context.Context, ticketID string) (*model.SuggestReplyResult, error) {
	panic(fmt.Errorf("not implemented: SuggestReply - suggestReply"))
}

// SearchDocuments is the resolver for the searchDocuments field.
func (r *queryResolver) SearchDocuments(ctx context.Context, query string, limit *int32) ([]*model.DocumentChunk, error) {
	panic(fmt.Errorf("not implemented: SearchDocuments - searchDocuments"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
