// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Document struct {
	ID              string `json:"id"`
	TenantID        string `json:"tenantId"`
	Title           string `json:"title"`
	SourceURI       string `json:"sourceUri"`
	CreatedByUserID string `json:"createdByUserId"`
	CreatedAt       string `json:"createdAt"`
}

type DocumentChunk struct {
	ID             string `json:"id"`
	DocumentID     string `json:"documentId"`
	ChunkIndex     int32  `json:"chunkIndex"`
	Content        string `json:"content"`
	EmbeddingModel string `json:"embeddingModel"`
}

type Query struct {
}

type SuggestReplyResult struct {
	SuggestedReply string           `json:"suggestedReply"`
	Sources        []*DocumentChunk `json:"sources"`
}

type Ticket struct {
	ID               string  `json:"id"`
	TenantID         string  `json:"tenantId"`
	Subject          string  `json:"subject"`
	Status           string  `json:"status"`
	CreatedByUserID  string  `json:"createdByUserId"`
	AssignedToUserID *string `json:"assignedToUserId,omitempty"`
	CreatedAt        string  `json:"createdAt"`
}
