// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    id,
    occurred_at,
    event_type,
    action,
    outcome,
    tenant_id,
    user_id,
    resource,
    resource_id,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type InsertAuditLogParams struct {
	ID         pgtype.UUID
	OccurredAt pgtype.Timestamptz
	EventType  string
	Action     string
	Outcome    string
	TenantID   pgtype.UUID
	UserID     pgtype.UUID
	Resource   string
	ResourceID string
	Metadata   []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.OccurredAt,
		arg.EventType,
		arg.Action,
		arg.Outcome,
		arg.TenantID,
		arg.UserID,
		arg.Resource,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}
