// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO knowledge_documents (
	id,
	tenant_id,
	title,
	source_uri,
	created_by_user_id,
	created_at
) VALUES (
	$1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_id, title, source_uri, created_by_user_id, created_at
`

type CreateDocumentParams struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Title           string
	SourceUri       string
	CreatedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (KnowledgeDocument, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.SourceUri,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i KnowledgeDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.SourceUri,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM knowledge_documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, tenant_id, title, source_uri, created_by_user_id, created_at
FROM knowledge_documents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (KnowledgeDocument, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i KnowledgeDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.SourceUri,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const insertDocumentChunk = `-- name: InsertDocumentChunk :exec
INSERT INTO document_chunks (
	id,
	document_id,
	tenant_id,
	chunk_index,
	content,
	embedding_model,
	embedding,
	created_at
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertDocumentChunkParams struct {
	ID             pgtype.UUID
	DocumentID     pgtype.UUID
	TenantID       pgtype.UUID
	ChunkIndex     int32
	Content        string
	EmbeddingModel string
	Embedding      pgvector.Vector
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertDocumentChunk(ctx context.Context, arg InsertDocumentChunkParams) error {
	_, err := q.db.Exec(ctx, insertDocumentChunk,
		arg.ID,
		arg.DocumentID,
		arg.TenantID,
		arg.ChunkIndex,
		arg.Content,
		arg.EmbeddingModel,
		arg.Embedding,
		arg.CreatedAt,
	)
	return err
}

const listDocumentsByTenant = `-- name: ListDocumentsByTenant :many
SELECT id, tenant_id, title, source_uri, created_by_user_id, created_at
FROM knowledge_documents
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]KnowledgeDocument, error) {
	rows, err := q.db.Query(ctx, listDocumentsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeDocument
	for rows.Next() {
		var i KnowledgeDocument
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.SourceUri,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimilarChunks = `-- name: SearchSimilarChunks :many
SELECT id, document_id, tenant_id, chunk_index, content, embedding_model, embedding, created_at
FROM document_chunks
WHERE tenant_id = $1
ORDER BY embedding <=> $2
LIMIT $3
`

type SearchSimilarChunksParams struct {
	TenantID  pgtype.UUID
	Embedding pgvector.Vector
	Limit     int32
}

func (q *Queries) SearchSimilarChunks(ctx context.Context, arg SearchSimilarChunksParams) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, searchSimilarChunks, arg.TenantID, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentChunk
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TenantID,
			&i.ChunkIndex,
			&i.Content,
			&i.EmbeddingModel,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
