// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AuditLog struct {
	ID         pgtype.UUID
	OccurredAt pgtype.Timestamptz
	EventType  string
	Action     string
	Outcome    string
	TenantID   pgtype.UUID
	UserID     pgtype.UUID
	Resource   string
	ResourceID string
	Metadata   []byte
}

type DocumentChunk struct {
	ID             pgtype.UUID
	DocumentID     pgtype.UUID
	TenantID       pgtype.UUID
	ChunkIndex     int32
	Content        string
	EmbeddingModel string
	Embedding      pgvector.Vector
	CreatedAt      pgtype.Timestamptz
}

type KnowledgeDocument struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Title           string
	SourceUri       string
	CreatedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

type Membership struct {
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Ticket struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	AssignedToUserID pgtype.UUID
	Subject          string
	Status           string
	CreatedByUserID  pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
