// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnsentOutboxEvents = `-- name: GetUnsentOutboxEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, created_at
FROM outbox
WHERE sent_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

type GetUnsentOutboxEventsRow struct {
	ID            pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUnsentOutboxEvents(ctx context.Context, limit int32) ([]GetUnsentOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getUnsentOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnsentOutboxEventsRow
	for rows.Next() {
		var i GetUnsentOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (
	id,
	aggregate_type,
	aggregate_id,
	event_type,
	payload
) VALUES (
	$1, $2, $3, $4, $5
)
`

type InsertOutboxEventParams struct {
	ID            pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const markOutboxEventSent = `-- name: MarkOutboxEventSent :exec
UPDATE outbox SET sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOutboxEventSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventSent, id)
	return err
}
