// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tickets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
	id,
	tenant_id,
	subject,
	status,
	created_by_user_id,
	assigned_to_user_id,
	created_at
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)
RETURNING id, tenant_id, subject, status, created_by_user_id, assigned_to_user_id, created_at
`

type CreateTicketParams struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	Subject          string
	Status           string
	CreatedByUserID  pgtype.UUID
	AssignedToUserID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

type CreateTicketRow struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	Subject          string
	Status           string
	CreatedByUserID  pgtype.UUID
	AssignedToUserID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (CreateTicketRow, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ID,
		arg.TenantID,
		arg.Subject,
		arg.Status,
		arg.CreatedByUserID,
		arg.AssignedToUserID,
		arg.CreatedAt,
	)
	var i CreateTicketRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.Status,
		&i.CreatedByUserID,
		&i.AssignedToUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, tenant_id, subject, status, created_by_user_id, assigned_to_user_id, created_at
FROM tickets
WHERE id = $1
LIMIT 1
`

type GetTicketByIDRow struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	Subject          string
	Status           string
	CreatedByUserID  pgtype.UUID
	AssignedToUserID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (GetTicketByIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i GetTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.Status,
		&i.CreatedByUserID,
		&i.AssignedToUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketsByTenant = `-- name: ListTicketsByTenant :many
SELECT id, tenant_id, subject, status, created_by_user_id, assigned_to_user_id, created_at
FROM tickets
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListTicketsByTenantRow struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	Subject          string
	Status           string
	CreatedByUserID  pgtype.UUID
	AssignedToUserID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListTicketsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListTicketsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listTicketsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsByTenantRow
	for rows.Next() {
		var i ListTicketsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Subject,
			&i.Status,
			&i.CreatedByUserID,
			&i.AssignedToUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET subject = $2,
	status = $3,
	assigned_to_user_id = $4
WHERE id = $1
RETURNING id, tenant_id, subject, status, created_by_user_id, assigned_to_user_id, created_at
`

type UpdateTicketParams struct {
	ID               pgtype.UUID
	Subject          string
	Status           string
	AssignedToUserID pgtype.UUID
}

type UpdateTicketRow struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	Subject          string
	Status           string
	CreatedByUserID  pgtype.UUID
	AssignedToUserID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (UpdateTicketRow, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Subject,
		arg.Status,
		arg.AssignedToUserID,
	)
	var i UpdateTicketRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.Status,
		&i.CreatedByUserID,
		&i.AssignedToUserID,
		&i.CreatedAt,
	)
	return i, err
}
